version: "2.3"

services:
  master:
    build:
      context: .
      dockerfile: master.Dockerfile
    image: sbeliakou/kind:master-1.16.2
    container_name: master
    hostname: master
    volumes:
    - /lib/modules:/lib/modules:ro
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /var/lib/containerd
    tmpfs:
    - /run
    - /tmp
    ports:
    - 9090:9090
    - 80:80
    - 443:443
    - 8443:6443
    privileged: true
    ipc: private
    tty: true
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    networks:
      k8slocal:
        ipv4_address: 172.31.0.2

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    image: sbeliakou/kind:node-1.16.2
    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/lib/containerd
    tmpfs:
      - /run
      - /tmp
    privileged: true
    ipc: private
    tty: true
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    depends_on:
      - master
    networks:
      k8slocal:

networks:
  k8slocal:
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/16
        gateway: 172.31.0.1
